import type { Lang } from "@/types";

export const API_URL =
  import.meta.env.VITE_API_URL || "https://pacta-iw8j.onrender.com/api";

export const DEFAULT_LANG: Lang = "en";

export const LANG_KEY = "pacta_language";
export const TOKEN_KEY = "pacta_token";
export const USER_KEY = "pacta_user";

export const WILAYAS = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Bejaia",
  "Biskra",
  "Bechar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tebessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Algiers",
  "Djelfa",
  "Jijel",
  "Setif",
  "Saida",
  "Skikda",
  "Sidi Bel Abbes",
  "Annaba",
  "Guelma",
  "Constantine",
  "Medea",
  "Mostaganem",
  "MSila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arreridj",
  "Boumerdes",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Ain Defla",
  "Naama",
  "Ain Temouchent",
  "Ghardaia",
  "Relizane",
  "El M'Ghair",
  "El Meniaa",
  "Ouled Djellal",
  "Bordj Badji Mokhtar",
  "Beni Abbes",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "Timimoun",
];

export const GUIDE_LANGUAGES = [
  "en",
  "ar",
  "fr",
  "es",
  "de",
  "it",
  "tr",
  "zh",
] as const;

export const GUIDE_SPECIALIZATIONS = [
  "historical",
  "cultural",
  "adventure",
  "nature",
  "food",
  "photography",
  "religious",
  "shopping",
  "nightlife",
  "desert",
  "mountain",
  "coastal",
] as const;

export const STATUS_COLORS: Record<string, string> = {
  pending: "bg-amber-50 text-amber-700 border-amber-200",
  confirmed: "bg-emerald-50 text-emerald-700 border-emerald-200",
  cancelled: "bg-rose-50 text-rose-700 border-rose-200",
  completed: "bg-gray-900 text-white border-gray-800",
  new: "bg-blue-50 text-blue-700 border-blue-200",
  read: "bg-gray-50 text-gray-600 border-gray-200",
  replied: "bg-purple-50 text-purple-700 border-purple-200",
  archived: "bg-gray-100 text-gray-400 border-gray-200",
};

export const ROLE_COLORS: Record<string, string> = {
  admin: "bg-purple-50 text-purple-700 border-purple-200",
  tourist: "bg-blue-50 text-blue-700 border-blue-200",
  hotel_owner: "bg-indigo-50 text-indigo-700 border-indigo-200",
  resort_owner: "bg-cyan-50 text-cyan-700 border-cyan-200",
  rental_owner: "bg-orange-50 text-orange-700 border-orange-200",
  guide: "bg-emerald-50 text-emerald-700 border-emerald-200",
};

export const TRANSLATIONS: Record<Lang, Record<string, any>> = {
  en: {
    appName: "Pacta",
    appTagline: "Tourism",
    nav: {
      home: "Home",
      explore: "Explore",
      categories: "Tourism Categories",
      network: "Our Network",
      dashboard: "Dashboard",
      profile: "My Profile",
      reservations: "My Reservations",
      wishlist: "Wishlist",
      notifications: "Notifications",
      contact: "Contact Us",
      login: "Login",
      register: "Get Started",
      logout: "Logout",
      settings: "Settings",
    },
    roles: {
      tourist: "Tourist",
      hotel_owner: "Hotel Owner",
      resort_owner: "Resort Owner",
      rental_owner: "Rental Owner",
      guide: "Tour Guide",
      admin: "Administrator",
    },
    auth: {
      loginTitle: "Welcome Back",
      loginSubtitle: "Sign in to manage your bookings and profile",
      registerTitle: "Create Account",
      nameLabel: "Full Name",
      emailLabel: "Email Address",
      passwordLabel: "Password",
      loginBtn: "Sign In",
      registerBtn: "Create Account",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      switchRegister: "Register here",
      switchLogin: "Login here",
      forgotPassword: "Forgot password?",
      resetPassword: "Reset Password",
      continue: "Continue",
      back: "Back",
      selectRole: "Select your account type",
      avatarRequired: "Please upload a profile photo",
      nameRequired: "Name is required",
      emailInvalid: "Please enter a valid email",
      passwordMin: "Password must be at least 6 characters",
      passwordMax: "Password cannot exceed 128 characters",
      serverError: "Server connection error. Please try again.",
      authFailed: "Authentication failed. Please check your credentials.",
    },
    dashboard: {
      admin: "Admin Dashboard",
      hotel: "Hotel Dashboard",
      resort: "Resort Dashboard",
      rental: "Rental Dashboard",
      guide: "Guide Dashboard",
      tourist: "My Reservations",
      totalReservations: "Total Reservations",
      totalRevenue: "Total Revenue",
      totalGuests: "Total Guests",
      pending: "Pending",
      confirmed: "Confirmed",
      completed: "Completed",
      cancelled: "Cancelled",
      bookings: "Bookings",
      revenue: "Revenue",
      guests: "Guests",
      capacity: "Capacity",
      active: "Active",
      contracts: "Contracts",
      tours: "Tours",
      tourists: "Tourists",
      statusDistribution: "Status Distribution",
      allReservations: "All Reservations",
      tourRequests: "Tour Requests",
      rentalInquiries: "Rental Inquiries",
      searchPlaceholder: "Search by name or reservation ID...",
      filterType: "All Types",
      filterStatus: "All Statuses",
      noResults: "No results found",
      id: "ID",
      touristLabel: "Tourist",
      provider: "Provider",
      type: "Type",
      date: "Date",
      amount: "Amount",
      status: "Status",
      action: "Action",
      confirm: "Confirm",
      reject: "Reject",
      viewDetails: "View Details",
      specialRequests: "Special Requests",
      reservationDetails: "Reservation Details",
      listingInfo: "Listing Information",
      guestInfo: "Guest Information",
      tenantInfo: "Tenant Information",
      propertyInfo: "Property Information",
      amenities: "Amenities",
      houseFeatures: "House Features",
      rentalRules: "Rental Rules",
      leisureActivities: "Leisure Activities",
      languages: "Languages",
      specializations: "Specializations",
      confirmCancel: "Are you sure you want to cancel this reservation?",
      cancelError: "Could not cancel reservation at this time.",
      reviewBtn: "Write Review",
      exploreNew: "Explore New",
    },
    listing: {
      priceNight: "per night",
      priceDay: "per day",
      checkIn: "Check-In Date",
      checkOut: "Check-Out Date",
      tourStart: "Tour Start",
      tourEnd: "Tour End",
      guests: "Guests",
      specialRequestsLabel: "Special Requests",
      totalPrice: "Total Price",
      bookNow: "Book Now",
      cashOnArrival: "Cash on Arrival",
      bookingSuccess: "Reservation created successfully! Redirecting...",
      bookingError: "Could not complete booking. Please check your inputs.",
      notFound: "Listing not found",
      backToExplore: "Back to Explore",
      verifiedBadge: "Verified",
      starRating: "Stars",
      roomsAvailable: "rooms available",
      maxGuests: "max guests",
      description: "Description",
      features: "Features",
      verifiedGuide: "Verified Guide",
    },
    profile: {
      title: "My Profile",
      accountInfo: "Account Information",
      security: "Security",
      businessProfile: "Business Profile",
      saveChanges: "Save Changes",
      updateCredentials: "Update Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      displayName: "Display Name",
      phone: "Phone",
      bio: "Bio",
      location: "Location",
      interfaceLanguage: "Interface Language",
      listingStatus: "Listing Status",
      activeDescription: "Active listings are visible to customers",
      nameEn: "Name (English)",
      nameAr: "Name (Arabic)",
      descEn: "Description (English)",
      descAr: "Description (Arabic)",
      price: "Price",
      wilaya: "Wilaya",
      roomsAvailable: "Rooms Available",
      propertyClass: "Star Rating",
      maxCapacity: "Max Capacity",
      maxGroupSize: "Max Group Size",
      verifiedGuideCode: "Verified Guide Code",
      expertiseEn: "Expertise (English)",
      expertiseAr: "Expertise (Arabic)",
      languagesSpoken: "Languages Spoken (comma-separated)",
      specializations: "Specializations (comma-separated)",
      structure: "Property Structure",
      houseFeatures: "House Features",
      rentalRules: "Rental Rules",
      leisureActivities: "Leisure Activities",
      successUpdate: "Profile updated successfully",
      errorUpdate: "Failed to update profile",
      passwordSuccess: "Password changed successfully",
      passwordError: "Failed to change password",
    },
    reservations: {
      title: "My Reservations",
      subtitle: "Track and manage your bookings across Algeria",
      noReservations: "No reservations found",
      startExploring: "Start exploring and book your next adventure",
      totalPrice: "Total Price",
      guestsLabel: "Guests",
      notesLabel: "Notes",
      cancelBtn: "Cancel",
      reviewBtn: "Write Review",
      duration: "Duration",
      provider: "Provider",
      status: {
        pending: "Pending Approval",
        confirmed: "Confirmed",
        cancelled: "Cancelled",
        completed: "Completed",
      },
    },
    contact: {
      title: "Contact Us",
      subtitle:
        "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
      name: "Your Name",
      email: "Email Address",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      success: "Message sent successfully!",
      error: "Failed to send message. Please try again.",
    },
    wishlist: {
      title: "My Wishlist",
      empty: "Your wishlist is empty",
      explore: "Explore listings to add to your wishlist",
      remove: "Remove",
      added: "Added",
    },
    notifications: {
      title: "Notifications",
      markAllRead: "Mark all as read",
      empty: "No notifications",
      newReservation: "New Reservation",
      confirmed: "Booking Confirmed",
      cancelled: "Booking Cancelled",
      completed: "Booking Completed",
      reviewReceived: "New Review",
    },
    common: {
      loading: "Loading...",
      error: "Something went wrong",
      retry: "Retry",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      create: "Create",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      all: "All",
      submit: "Submit",
      close: "Close",
      confirm: "Confirm",
      yes: "Yes",
      no: "No",
      next: "Next",
      previous: "Previous",
      of: "of",
      showing: "Showing",
      results: "results",
      perPage: "per page",
    },
    footer: {
      destinations: "Destinations",
      services: "Services",
      contact: "Contact",
      terms: "Terms",
      privacy: "Privacy",
      rights: "All rights reserved",
    },
    hero: {
      featured: "Featured Deal",
      exploreNow: "Explore Now",
      browseByType: "Browse by Tourism Type",
      verifiedProviders: "Verified Network Providers",
      testimonials: "What Travelers Say",
      communityFeedback: "Community Feedback",
    },
    providers: {
      hotels: "Hotels",
      resorts: "Resorts",
      guides: "Tourist Guides",
      rentals: "Home Rentals",
      bookDirect: "Book Direct Now",
      viewDetails: "View Full Details",
    },
  },
  ar: {
    appName: "باكتا",
    appTagline: "للسياحة",
    nav: {
      home: "الرئيسية",
      explore: "استكشف",
      categories: "أنواع السياحة",
      network: "شبكتنا",
      dashboard: "لوحة التحكم",
      profile: "ملفي الشخصي",
      reservations: "حجوزاتي",
      wishlist: "المفضلة",
      notifications: "الإشعارات",
      contact: "اتصل بنا",
      login: "تسجيل الدخول",
      register: "ابدأ الآن",
      logout: "تسجيل الخروج",
      settings: "الإعدادات",
    },
    roles: {
      tourist: "سائح",
      hotel_owner: "صاحب فندق",
      resort_owner: "صاحب منتجع",
      rental_owner: "صاحب عقار",
      guide: "مرشد سياحي",
      admin: "مدير النظام",
    },
    auth: {
      loginTitle: "مرحباً بعودتك",
      loginSubtitle: "قم بتسجيل الدخول لإدارة حجوزاتك وملفك",
      registerTitle: "إنشاء حساب جديد",
      nameLabel: "الاسم الكامل",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      loginBtn: "تسجيل الدخول",
      registerBtn: "إنشاء الحساب",
      noAccount: "ليس لديك حساب؟",
      hasAccount: "لديك حساب بالفعل؟",
      switchRegister: "سجل الآن",
      switchLogin: "سجل دخولك",
      forgotPassword: "نسيت كلمة المرور؟",
      resetPassword: "إعادة تعيين كلمة المرور",
      continue: "متابعة",
      back: "رجوع",
      selectRole: "اختر نوع حسابك",
      avatarRequired: "يرجى رفع صورة شخصية",
      nameRequired: "الاسم مطلوب",
      emailInvalid: "يرجى إدخال بريد إلكتروني صحيح",
      passwordMin: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      passwordMax: "لا يمكن أن تتجاوز كلمة المرور 128 حرفاً",
      serverError: "خطأ في الاتصال بالخادم. يرجى المحاولة مرة أخرى.",
      authFailed: "فشل المصادقة. يرجى التحقق من بياناتك.",
    },
    dashboard: {
      admin: "لوحة تحكم المشرف",
      hotel: "لوحة تحكم الفندق",
      resort: "لوحة تحكم المنتجع",
      rental: "لوحة تحكم الإيجار",
      guide: "لوحة تحكم المرشد",
      tourist: "حجوزاتي",
      totalReservations: "إجمالي الحجوزات",
      totalRevenue: "إجمالي الإيرادات",
      totalGuests: "إجمالي الضيوف",
      pending: "قيد الانتظار",
      confirmed: "مؤكد",
      completed: "مكتمل",
      cancelled: "ملغي",
      bookings: "الحجوزات",
      revenue: "الإيرادات",
      guests: "الضيوف",
      capacity: "السعة",
      active: "نشط",
      contracts: "العقود",
      tours: "الجولات",
      tourists: "السياح",
      statusDistribution: "توزيع الحالات",
      allReservations: "جميع الحجوزات",
      tourRequests: "طلبات الجولات",
      rentalInquiries: "طلبات الإيجار",
      searchPlaceholder: "بحث بالاسم أو رقم الحجز...",
      filterType: "كل الأنواع",
      filterStatus: "كل الحالات",
      noResults: "لا توجد نتائج",
      id: "الرقم",
      touristLabel: "السائح",
      provider: "مزود الخدمة",
      type: "النوع",
      date: "التاريخ",
      amount: "المبلغ",
      status: "الحالة",
      action: "إجراء",
      confirm: "تأكيد",
      reject: "رفض",
      viewDetails: "عرض التفاصيل",
      specialRequests: "طلبات خاصة",
      reservationDetails: "تفاصيل الحجز",
      listingInfo: "معلومات القائمة",
      guestInfo: "معلومات الضيف",
      tenantInfo: "معلومات المستأجر",
      propertyInfo: "معلومات العقار",
      amenities: "وسائل الراحة",
      houseFeatures: "مميزات المنزل",
      rentalRules: "قواعد الإيجار",
      leisureActivities: "الأنشطة الترفيهية",
      languages: "اللغات",
      specializations: "التخصصات",
      confirmCancel: "هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟",
      cancelError: "تعذر إلغاء الحجز في الوقت الحالي.",
      reviewBtn: "كتابة تقييم",
      exploreNew: "استكشف الجديد",
    },
    listing: {
      priceNight: "لليلة",
      priceDay: "ليوم",
      checkIn: "تاريخ الوصول",
      checkOut: "تاريخ المغادرة",
      tourStart: "بداية الجولة",
      tourEnd: "نهاية الجولة",
      guests: "الضيوف",
      specialRequestsLabel: "طلبات خاصة",
      totalPrice: "السعر الإجمالي",
      bookNow: "احجز الآن",
      cashOnArrival: "الدفع عند الوصول",
      bookingSuccess: "تم إنشاء الحجز بنجاح! جاري التوجيه...",
      bookingError: "تعذر إتمام الحجز. يرجى التحقق من المدخلات.",
      notFound: "القائمة غير موجودة",
      backToExplore: "العودة للاستكشاف",
      verifiedBadge: "معتمد",
      starRating: "نجوم",
      roomsAvailable: "غرف متاحة",
      maxGuests: "حد أقصى للضيوف",
      description: "الوصف",
      features: "المميزات",
      verifiedGuide: "مرشد معتمد",
    },
    profile: {
      title: "ملفي الشخصي",
      accountInfo: "المعلومات الأساسية",
      security: "الأمان",
      businessProfile: "الملف التجاري",
      saveChanges: "حفظ التغييرات",
      updateCredentials: "تحديث كلمة المرور",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      displayName: "الاسم المعروض",
      phone: "الهاتف",
      bio: "نبذة",
      location: "الموقع",
      interfaceLanguage: "لغة الواجهة",
      listingStatus: "حالة القائمة",
      activeDescription: "القوائم النشطة مرئية للعملاء",
      nameEn: "الاسم (بالإنجليزية)",
      nameAr: "الاسم (بالعربية)",
      descEn: "الوصف (بالإنجليزية)",
      descAr: "الوصف (بالعربية)",
      price: "السعر",
      wilaya: "الولاية",
      roomsAvailable: "الغرف المتاحة",
      propertyClass: "التصنيف بالنجوم",
      maxCapacity: "السعة القصوى",
      maxGroupSize: "الحد الأقصى للمجموعة",
      verifiedGuideCode: "رمز المرشد المعتمد",
      expertiseEn: "الخبرة (بالإنجليزية)",
      expertiseAr: "الخبرة (بالعربية)",
      languagesSpoken: "اللغات المتحدث بها (مفصولة بفاصلة)",
      specializations: "التخصصات (مفصولة بفاصلة)",
      structure: "هيكل العقار",
      houseFeatures: "مميزات المنزل",
      rentalRules: "قواعد الإيجار",
      leisureActivities: "الأنشطة الترفيهية",
      successUpdate: "تم تحديث الملف الشخصي بنجاح",
      errorUpdate: "فشل تحديث الملف الشخصي",
      passwordSuccess: "تم تغيير كلمة المرور بنجاح",
      passwordError: "فشل تغيير كلمة المرور",
    },
    reservations: {
      title: "حجوزاتي",
      subtitle: "تتبع وإدارة حجوزاتك في الجزائر",
      noReservations: "لم يتم العثور على حجوزات",
      startExploring: "ابدأ الاستكشاف واحجز مغامرتك القادمة",
      totalPrice: "السعر الإجمالي",
      guestsLabel: "الضيوف",
      notesLabel: "ملاحظات",
      cancelBtn: "إلغاء",
      reviewBtn: "كتابة تقييم",
      duration: "المدة",
      provider: "مزود الخدمة",
      status: {
        pending: "قيد الانتظار",
        confirmed: "مؤكد",
        cancelled: "ملغي",
        completed: "مكتمل",
      },
    },
    contact: {
      title: "اتصل بنا",
      subtitle: "نود سماع رأيك. أرسل لنا رسالة وسنرد في أقرب وقت ممكن.",
      name: "اسمك",
      email: "البريد الإلكتروني",
      subject: "الموضوع",
      message: "الرسالة",
      send: "إرسال الرسالة",
      success: "تم إرسال الرسالة بنجاح!",
      error: "فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.",
    },
    wishlist: {
      title: "المفضلة",
      empty: "المفضلة فارغة",
      explore: "استكشف القوائم لإضافتها للمفضلة",
      remove: "إزالة",
      added: "تمت الإضافة",
    },
    notifications: {
      title: "الإشعارات",
      markAllRead: "تعيين الكل كمقروء",
      empty: "لا توجد إشعارات",
      newReservation: "حجز جديد",
      confirmed: "تم تأكيد الحجز",
      cancelled: "تم إلغاء الحجز",
      completed: "تم إنجاز الحجز",
      reviewReceived: "تقييم جديد",
    },
    common: {
      loading: "جاري التحميل...",
      error: "حدث خطأ ما",
      retry: "إعادة المحاولة",
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      create: "إنشاء",
      search: "بحث",
      filter: "تصفية",
      sort: "ترتيب",
      all: "الكل",
      submit: "إرسال",
      close: "إغلاق",
      confirm: "تأكيد",
      yes: "نعم",
      no: "لا",
      next: "التالي",
      previous: "السابق",
      of: "من",
      showing: "عرض",
      results: "نتيجة",
      perPage: "لكل صفحة",
    },
    footer: {
      destinations: "وجهات",
      services: "خدمات",
      contact: "اتصل بنا",
      terms: "الشروط",
      privacy: "الخصوصية",
      rights: "جميع الحقوق محفوظة",
    },
    hero: {
      featured: "عرض مميز",
      exploreNow: "اكتشف الآن",
      browseByType: "تصفح حسب نوع السياحة",
      verifiedProviders: "شركاؤنا المعتمدون",
      testimonials: "ماذا يقول المسافرون",
      communityFeedback: "آراء المجتمع",
    },
    providers: {
      hotels: "الفنادق",
      resorts: "المنتجعات",
      guides: "المرشدين السياحيين",
      rentals: "عقارات للإيجار",
      bookDirect: "احجز مباشرة",
      viewDetails: "عرض التفاصيل",
    },
  },
};
