/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        /* PACTA Brand Colors */
        pacta: {
          navy: {
            DEFAULT: "#0C2D4D",
            light: "#164570",
            dark: "#061E33",
            50: "#E8F0F7",
            100: "#D1E1EF",
            200: "#A3C3DF",
            300: "#75A5CF",
            400: "#4787BF",
            500: "#1969AF",
            600: "#0C2D4D",
            700: "#164570",
            800: "#0D2D4A",
            900: "#061E33",
          },
          gold: {
            DEFAULT: "#D4942A",
            light: "#E8B84D",
            dark: "#B0781F",
            50: "#FDF6E8",
            100: "#FBEED0",
            200: "#F7DDA1",
            300: "#F3CC72",
            400: "#EFBB43",
            500: "#D4942A",
            600: "#B0781F",
            700: "#8C5F18",
            800: "#684611",
            900: "#442D0A",
          },
          green: {
            DEFAULT: "#2D7A5F",
            light: "#3D9E7A",
            dark: "#1F5C44",
            50: "#E8F5F0",
            100: "#D1EBE1",
            200: "#A3D7C3",
            300: "#75C3A5",
            400: "#47AF87",
            500: "#2D7A5F",
            600: "#1F5C44",
            700: "#174A35",
            800: "#0F3827",
            900: "#072619",
          },
          teal: {
            DEFAULT: "#1A7A6E",
            light: "#249E8F",
            dark: "#115C52",
            50: "#E6F5F3",
            100: "#CCEBE7",
            200: "#99D7CF",
            300: "#66C3B7",
            400: "#33AF9F",
            500: "#1A7A6E",
            600: "#115C52",
            700: "#0D4A42",
            800: "#093832",
            900: "#052622",
          },
          ocean: {
            DEFAULT: "#1A7A9E",
            light: "#2A9BC4",
            dark: "#135A78",
            50: "#E8F4F8",
            100: "#D1E9F1",
            200: "#A3D3E3",
            300: "#75BDD5",
            400: "#47A7C7",
            500: "#1A7A9E",
            600: "#135A78",
            700: "#0F4860",
            800: "#0B3648",
            900: "#072430",
          },
          sand: {
            DEFAULT: "#F5EFE6",
            light: "#FAF7F2",
            dark: "#E8DFD0",
            50: "#FDFCFA",
            100: "#FAF7F2",
            200: "#F5EFE6",
            300: "#E8DFD0",
            400: "#D9CDB8",
            500: "#C8B89C",
            600: "#B5A080",
            700: "#A28A68",
            800: "#8F7450",
            900: "#7C5E38",
          },
          cream: {
            DEFAULT: "#FAF8F5",
            light: "#FEFDFB",
            dark: "#F5F0E8",
          },
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}